### ISSUE TITLE
The addon doesn't work in Youtube with the last version of Mozilla Firefox

### ISSUE THREAD

**Issue by Carlos-EstebanM** [maxe-hsieh/subtitle_reader#10]
If an user of Firefox open a video in YouTube and enable the subtitles, the addon can't read. Tested with Firefox 115.0.2 (64-bit).
ERROR - unhandled exception (09:57:57.526) - MainThread (6740):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 768, in Notify
  File "C:\Users\carlo\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 183, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
  File "C:\Users\carlo\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 72, in getSubtitle
    self.get_subtitle_object()
  File "C:\Users\carlo\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 85, in get_subtitle_object
    self.onFoundSubtitleObject(obj)
  File "C:\Users\carlo\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in onFoundSubtitleObject
    subtitle = getattr(self, browser + 'GetSubtitle')(obj)
  File "C:\Users\carlo\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 141, in firefoxGetSubtitle
    return self.processSubtitle(subtitle)
AttributeError: 'Youtube' object has no attribute 'processSubtitle'

**Comment by maxe-hsieh** [comment]
Fixed on 2.82
