### ISSUE TITLE
YouTube：播放带有聊天室的直播回放视频时报错，可能是网站结构发生变化。

### ISSUE THREAD

**Issue by hwf1324** [maxe-hsieh/subtitle_reader#26]
以下是日志，似乎是没有找到指定的对象。

```log
ERROR - unhandled exception (20:42:04.146) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.295) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.382) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.491) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.591) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.689) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.816) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:04.947) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:05.030) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:05.128) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:05.242) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:05.383) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
ERROR - unhandled exception (20:42:05.493) - MainThread (11216):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 986, in Notify
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\__init__.py", line 279, in readSubtitle
    subtitle = self.subtitleAlg.getSubtitle()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 94, in getSubtitle
    self.readVoting()
  File "C:\Users\hwf1324\AppData\Roaming\nvda\addons\subtitle_reader\globalPlugins\subtitle_reader\youtube.py", line 325, in readVoting
    votingObj = self.chatRoom.firstChild.next.next
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
```

**Comment by maxe-hsieh** [comment]
我測試回放沒發現錯誤，可否提供您的測試影片呢？

**Comment by hwf1324** [comment]
视频：https://www.youtube.com/watch?v=fjD2CVG9UBo&ab_channel=%E6%82%9F%E8%A8%A2

Chrome：版本 129.0.6668.101（正式版本） （64 位）

NVDA：版本：alpha-34581,32245d46（2025.1.0.34581）

字幕阅读器：版本：3.1

**Comment by maxe-hsieh** [comment]
我仍然無法重現問題，請問是否能夠找出重現問題的步驟呢

**Comment by maxe-hsieh** [comment]
字幕閱讀器支援的 NVDA 最新版本為 2024.4.1 在此版本無法重現您的問題。
若該問題只在 NVDA Alpha 版本出現，那麼字幕閱讀器並不支援此版本，因為 Alpha 隨時會進行許多不確定的修改，字幕閱讀器不打算隨時跟著這樣的變化。
